### ISSUE TITLE
connect failed: ETIMEDOUT

### ISSUE THREAD

**Issue by shankar667** [fyhertz/libstreaming#237]
Hi,
I am using example-3 and getting the error: connect failed: ETIMEDOUT, please see log below: 

`D/RtspClient: Connecting to RTSP server...`
`I/RtspClient: TEARDOWN rtsp://192.168.0.42:1935/live/myStream RTSP/1.0`
`W/System.err: java.net.ConnectException: failed to connect to /192.168.0.42 (port 1935): connect failed: ETIMEDOUT (Connection timed out)`

and also installed the Wowza Streaming Engine locally and created a "Source Authentication".

anything missing?

**Comment by ahmadeqbal** [comment]
maybe you'r firewall is refusing the connection
have you opened 1935 port on you'r local machine?

**Comment by nthapa13** [comment]
I had the same problem yesterday, my computer's IP was 192.168.0.5 and wowza server's IP was 192.168.26.1, I could access the wowza IP from my machine but not from my mobile phone. So I just installed wowza in a remote computer with a public IP and now it works. I couldnt resolve the problem locally. I dont think the problem is in the code but the problem is somewhere in the network setup, most probably firewall setup.

**Comment by ahmadeqbal** [comment]
follow this link to open the port on you'r local computer
http://www.wikihow.com/Open-Ports

**Comment by shankar667** [comment]
Thank you so much for letting me know, I found, the issue comes from firewall

**Comment by shankar667** [comment]
Issue fixed by modifying firewall settings. Thank you!
